name: Fly Deploy
on: 
  push:
  schedule:
    - cron: '0 4 1 * *'
env:
  FLY_API_TOKEN: HFypQNtAoth8dZTchbPeT0DRycO0E3gKTpBvUKFo_9Q
  APP_NAME: vf24
  UUID: 98fb39a0-5d5f-4ea9-aced-9068b3ce0317
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          sh ./deploy.sh
